/*
 * AlgebraSetup.java
 *
 * Created on 13 maart 2007, 15:05
 */

package edu.rug.hep.simplie.ui;

import edu.rug.hep.simplie.Globals;
import edu.rug.hep.simplie.dynkindiagram.*;

import Jama.Matrix.*;

/**
 *
 * @author  Teake Nutma
 */
public class AlgebraSetup extends javax.swing.JPanel implements DiagramListener
{
	/** Creates new form LevelDecompositionUI */
	public AlgebraSetup()
	{
		initComponents();
		Globals.dd.addListener(this);
		algebraInfo.SetTitle("Full algebra");
		subAlgebraInfo.SetTitle("Regular subalgebra");
		disAlgebraInfo.SetTitle("Disconnected subalgebra");
		coAlgebraInfo.SetTitle("Co-subalgebra (regular x disconnected)");
	}
	
	public void diagramChanged()
	{
		algebraInfo.Update(Globals.group);
		subAlgebraInfo.Update(Globals.subGroup);
		disAlgebraInfo.Update(Globals.disGroup);
		coAlgebraInfo.Update(Globals.coGroup);
	
		dynkinDiagramPanel.setTitle("Dynkin Diagram of " + Globals.getDynkinDiagramType());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        algebraInfo = new edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo();
        subAlgebraInfo = new edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo();
        disAlgebraInfo = new edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo();
        coAlgebraInfo = new edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo();
        dynkinDiagramPanel = new edu.rug.hep.simplie.ui.DynkinDiagramPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dynkinDiagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disAlgebraInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(algebraInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subAlgebraInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(coAlgebraInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynkinDiagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(algebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subAlgebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coAlgebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disAlgebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo algebraInfo;
    private edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo coAlgebraInfo;
    private edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo disAlgebraInfo;
    private edu.rug.hep.simplie.ui.DynkinDiagramPanel dynkinDiagramPanel;
    private edu.rug.hep.simplie.ui.reusable.UIAlgebraInfo subAlgebraInfo;
    // End of variables declaration//GEN-END:variables
}
