/*
 * AlgebraSetup.java
 *
 * Created on 13 maart 2007, 15:05
 */

package tan.leveldecomposition.ui;

import tan.leveldecomposition.dynkindiagram.*;
import tan.leveldecomposition.group.*;
import tan.leveldecomposition.*;

import Jama.Matrix.*;

/**
 *
 * @author  Teake Nutma
 */
public class AlgebraSetup extends javax.swing.JPanel
{
	/** Creates new form LevelDecompositionUI */
	public AlgebraSetup()
	{
		initComponents();
		dynkinDiagramPanel.Initialize(this);
		Update();
		algebraInfo.SetTitle("Algebra information");
		subAlgebraInfo.SetTitle("Subalgebra information");
	}
	
	public void Update()
	{
		Globals.group		= new CGroup(DynkinDiagram.GetCartanMatrix());
		Globals.subGroup	= new CGroup(DynkinDiagram.GetCartanSubMatrix());
		
		algebraInfo.SetType(Globals.group.type);
		algebraInfo.SetRank(Globals.group.rank);
		algebraInfo.SetDim(Globals.group.dimension);
		algebraInfo.SetCMDet(Globals.group.det);
		
		subAlgebraInfo.SetType(Globals.subGroup.type);
		subAlgebraInfo.SetRank(Globals.subGroup.rank);
		subAlgebraInfo.SetDim(Globals.subGroup.dimension);
		subAlgebraInfo.SetCMDet(Globals.subGroup.det);
		
		TabbedPaneCartanMatrix.setTitleAt(2,"Subalgebra inverse * " + (Globals.subGroup.rank+1));
		
		taCartanMatrix.setText(Globals.matrixToString(DynkinDiagram.GetCartanMatrix(), 0));
		taCartanSubMatrix.setText(Globals.matrixToString(DynkinDiagram.GetCartanSubMatrix(), 0));
		taCartanSubInvMatrix.setText(Globals.matrixToString(DynkinDiagram.GetCartanSubMatrix().inverse().times(Globals.subGroup.rank+1), 1));
		
		dynkinDiagramPanel.repaint();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        PanelDynkinDiagram = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dynkinDiagramPanel = new tan.leveldecomposition.ui.DynkinDiagramPanel();
        PanelCartanMatrix = new javax.swing.JPanel();
        TabbedPaneCartanMatrix = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCartanMatrix = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taCartanSubMatrix = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taCartanSubInvMatrix = new javax.swing.JTextArea();
        algebraInfo = new tan.leveldecomposition.ui.reusable.UIAlgebraInfo();
        subAlgebraInfo = new tan.leveldecomposition.ui.reusable.UIAlgebraInfo();

        PanelDynkinDiagram.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dynkin Diagram", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));

        jScrollPane1.setViewportView(dynkinDiagramPanel);

        javax.swing.GroupLayout PanelDynkinDiagramLayout = new javax.swing.GroupLayout(PanelDynkinDiagram);
        PanelDynkinDiagram.setLayout(PanelDynkinDiagramLayout);
        PanelDynkinDiagramLayout.setHorizontalGroup(
            PanelDynkinDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDynkinDiagramLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDynkinDiagramLayout.setVerticalGroup(
            PanelDynkinDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDynkinDiagramLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelCartanMatrix.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartan Matrices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));
        taCartanMatrix.setColumns(20);
        taCartanMatrix.setEditable(false);
        taCartanMatrix.setFont(new java.awt.Font("Monospaced", 0, 12));
        taCartanMatrix.setRows(5);
        jScrollPane2.setViewportView(taCartanMatrix);

        TabbedPaneCartanMatrix.addTab("Full algebra", jScrollPane2);

        taCartanSubMatrix.setColumns(20);
        taCartanSubMatrix.setEditable(false);
        taCartanSubMatrix.setFont(new java.awt.Font("Monospaced", 0, 12));
        taCartanSubMatrix.setRows(5);
        jScrollPane3.setViewportView(taCartanSubMatrix);

        TabbedPaneCartanMatrix.addTab("Subalgebra", jScrollPane3);

        taCartanSubInvMatrix.setColumns(20);
        taCartanSubInvMatrix.setFont(new java.awt.Font("Monospaced", 0, 12));
        taCartanSubInvMatrix.setRows(5);
        jScrollPane4.setViewportView(taCartanSubInvMatrix);

        TabbedPaneCartanMatrix.addTab("Subalgebra inverse", jScrollPane4);

        javax.swing.GroupLayout PanelCartanMatrixLayout = new javax.swing.GroupLayout(PanelCartanMatrix);
        PanelCartanMatrix.setLayout(PanelCartanMatrixLayout);
        PanelCartanMatrixLayout.setHorizontalGroup(
            PanelCartanMatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCartanMatrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCartanMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCartanMatrixLayout.setVerticalGroup(
            PanelCartanMatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCartanMatrixLayout.createSequentialGroup()
                .addComponent(TabbedPaneCartanMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(algebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subAlgebraInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDynkinDiagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCartanMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {algebraInfo, subAlgebraInfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(algebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subAlgebraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDynkinDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelCartanMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCartanMatrix;
    private javax.swing.JPanel PanelDynkinDiagram;
    private javax.swing.JTabbedPane TabbedPaneCartanMatrix;
    private tan.leveldecomposition.ui.reusable.UIAlgebraInfo algebraInfo;
    private tan.leveldecomposition.ui.DynkinDiagramPanel dynkinDiagramPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private tan.leveldecomposition.ui.reusable.UIAlgebraInfo subAlgebraInfo;
    private javax.swing.JTextArea taCartanMatrix;
    private javax.swing.JTextArea taCartanSubInvMatrix;
    private javax.swing.JTextArea taCartanSubMatrix;
    // End of variables declaration//GEN-END:variables
	
}
