/*
 * UILevelTextfield.java
 *
 * Created on 14 maart 2007, 9:33
 */

package tan.leveldecomposition.ui.reusable;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import tan.leveldecomposition.helper.*;
import javax.swing.event.*;

/**
 *
 * @author  Teake Nutma
 */
public class UILevelTextfield extends javax.swing.JPanel
{
    private UILevelTextfield linkedTo;
    private int previousValue;
    
    /**
     * Creates new form UILevelTextfield
     */
    public UILevelTextfield()
    {
	initComponents();
	
	linkedTo = null;
	previousValue = GetValue();
	
	tfLevel.getDocument().addDocumentListener(new DocumentListener()
	{
	    public void removeUpdate(DocumentEvent e)
	    {
		UpdateLinked();
	    }
	    public void insertUpdate(DocumentEvent e)
	    {
		UpdateLinked();
	    }
	    public void changedUpdate(DocumentEvent e)
	    {
		
	    }
	});
	
	tfLevel.addKeyListener(new KeyListener()
	{
	    public void keyPressed(KeyEvent e)
	    {
	    }
	    public void keyReleased(KeyEvent e)
	    {
	    }
	    public void keyTyped(KeyEvent e)
	    {
		int k=e.getKeyChar();
		if((k>47 && k<58)||(k==8))
		{
		}
		else
		{
		    e.setKeyChar((char)KeyEvent.VK_CLEAR);
		}
	    }
	});
    }
    
    public void SetLabel(String label)
    {
	labelLevel.setText(label);
    }
    public int GetValue()
    {
	String value = tfLevel.getText();
	if(value.length() == 0) value = "0";
	return Integer.parseInt(value);
    }
    
    public void SetValue(int value)
    {
	tfLevel.setText(Helper.IntToString(value));
    }
    
    public void LinkTo(UILevelTextfield linkTo)
    {
	linkedTo = linkTo;
    }
    
    private void UpdateLinked()
    {
	if(linkedTo != null && (tfLevel.isFocusOwner() || buttonMinus.isFocusOwner() || buttonPlus.isFocusOwner() ) )
	{
	    int diff = GetValue() - previousValue;
	    if(linkedTo != null)
		linkedTo.SetValue(linkedTo.GetValue()+diff);
	    previousValue = GetValue();
	}
	previousValue = GetValue();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        labelLevel = new javax.swing.JLabel();
        tfLevel = new javax.swing.JTextField();
        buttonPlus = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();

        labelLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLevel.setText("Level:");

        tfLevel.setText("0");

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPlus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMinus)
                    .addComponent(buttonPlus)
                    .addComponent(tfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLevel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonPlusActionPerformed
    {//GEN-HEADEREND:event_buttonPlusActionPerformed
	SetValue(GetValue()+1);
    }//GEN-LAST:event_buttonPlusActionPerformed
    
    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonMinusActionPerformed
    {//GEN-HEADEREND:event_buttonMinusActionPerformed
	SetValue(GetValue()-1);
    }//GEN-LAST:event_buttonMinusActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JLabel labelLevel;
    private javax.swing.JTextField tfLevel;
    // End of variables declaration//GEN-END:variables
    
}
